export const REPORT_LABELS = {
  reportSubtitle: 'Análise de Composição Corporal',
  section1: 'Análise da Composição Corporal',
  moisture: 'Água Corporal',
  protein: 'Proteína',
  minerals: 'Minerais',
  bodyFat: 'Gordura Corporal',
  section2: 'Análise de Músculo e Gordura',
  weight: 'Peso',
  skeletalMuscle: 'Músculo Esquelético',
  visceralFat: 'Gordura Visceral',
  section3: 'Análise de Sobrepeso',
  bmi: 'IMC',
  bodyFatPct: 'Percentual de Gordura',
  waistHip: 'Relação Cintura/Quadril',
  section4: 'Músculos Segmentares',
  section5: 'Avaliação Geral',
  section6: 'Controle de Peso',
  section7: 'Evolução — Últimas avaliações',
  zoneLow: 'Baixo',
  zoneNormal: 'Normal',
  zoneOver: 'Alto',
  evalUnder: 'Abaixo',
  evalNormal: 'Normal',
  evalOver: 'Acima',
  evalWeight: 'Peso',
  evalMuscle: 'Músculo',
  evalBodyFat: 'Gordura',
  evalObesity: 'Obesidade',
  targetWeight: 'Peso Alvo',
  weightControl: 'Controle de Peso',
  bmr: 'Taxa Metabólica Basal (TMB)',
  score: 'Pontuação Geral',
  sideLeft: '(E)',
  sideRight: '(D)',
  chartWeight: 'Peso (kg)',
  chartMuscle: 'Massa Muscular Esquelética (kg)',
  chartFat: 'Percentual de Gordura Corporal (%)',
} as const;
